#include <iostream>
#include <string>
using namespace std;

// LeetCode Problem 389: Find the Difference
// Problem: Given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling string s and then adding one more letter at a random position.
// Find the letter that was added to t.
class Solution {
public:
    char findTheDifference(string s, string t) {
        char result = 0;

        for (char c : s) {
            result ^= c;
        }

        for (char c : t) {
            result ^= c;
        }

        return result;
    }
};

// end of leetcode/389.cpp

int main() {
    string s, t;
    cout << "Enter string s: ";
    cin >> s;

    cout << "Enter string t (with one extra character): ";
    cin >> t;

    Solution sol;
    char addedChar = sol.findTheDifference(s, t);

    cout << "The added character is: " << addedChar << endl;

    return 0;
}
